=== CRModders/CRM-2/spec/revision-2/schema.json
{
	"$schema": "http://json-schema.org/draft-07/schema#",
	"title": "Cosmic Reach Modpack Schema",
	"description": "Schema for a cosmic reach modpack file",
	"type": "object",
	"required": ["spec_revision", "name", "loader", "version", "files"],
	"properties": {
		"spec_revision": {
			"type": "number",
			"description": "The revision of the spec your modpack is using"
		},
		"name": {
			"type": "string",
			"description": "The name of your modpack"
		},
		"version": {
			"type": "string",
			"description": "The version identifier of the modpack"
		},
		"description": {
			"type": "string",
			"description": "The description of the modpack (Optional)"
		},
		"icon": {
			"type": "string",
			"description": "The URL of the modpack's icon. Can be either a http URL or a path to image file relative to the root of modpack's zip (Optional)"
		},
		"base_url": {
			"type": "string",
			"description": "The base url for the modpack file downloads (Optional, Required when using relative urls)"
		},
		"loader": {
			"type": "string",
			"enum": ["vanilla", "cosmic-quilt", "puzzle"],
			"description": "The name of the mod loader"
		},
		"files": {
			"type": "array",
			"description": "List of files to download",
			"items": {
				"$ref": "#/definitions/FileContent"
			}
		},
		"dependencies": {
			"type": "object",
			"description": "The dependencies of the modpack"
		}
	},
	"definitions": {
		"FileContent": {
			"type": "object",
			"properties": {
				"type": {
					"$ref": "#/definitions/ModTypeContent"
				},
				"id": {
					"type": "string",
					"description": "The identifier of the mod (FilePath safe)",
					"pattern": "^[a-zA-Z0-9-_.+]+$"
				},
				"version": {
					"type": "string",
					"description": "The version of the mod (FilePath safe)",
					"pattern": "^[a-zA-Z0-9-_.+]+$"
				},
				"sha512_hash": {
					"type": "string",
					"description": "The sha512 hash of the file",
					"pattern": "^[a-f0-9]{128}$"
				},
				"env": {
					"$ref": "#/definitions/EnvContent"
				},
				"download_url": {
					"type": "string",
					"description": "The download url of the file"
				}
			},
			"required": [
				"type",
				"id",
				"version",
				"sha512_hash",
				"env",
				"download_url"
			]
		},
		"EnvContent": {
			"type": "object",
			"properties": {
				"client": {
					"type": "string",
					"enum": ["required", "optional"],
					"description": "Whether the mod is required on client side or not"
				},
				"server": {
					"type": "string",
					"enum": ["required", "optional"],
					"description": "Whether the mod is required on server side or not"
				}
			},
			"required": ["server", "client"]
		},
		"ModTypeContent": {
			"type": "string",
			"enum": ["mod", "datamod"],
			"description": "The type of the mod"
		}
	}
}

=== CRModders/CRM-2/spec/revision-2/pack.json
{
	"$schema": "https://www.crmodders.dev/crm-2/revision-2/schema.json",
	"spec_revision": 2,
	"name": "The Awesome Modpack",
	"version": "0.1.4-beta",
	"description": "This is just a modpack :)",
	"loader": "cosmic-quilt",
	"base_url": "https://api.crmm.tech/api/cdn/data",
	"files": [
		{
			"type": "mod",
			"id": "simply-cosmic-shading",
			"version": "0.1.6+cr0.3.0",
			"sha512_hash": "bc7c4572f4acc893a575667fd4385f139142f4861bacee4f64f4672a2f3ace7d554fce86fd5055b52c9c530be370f6c5d80ec4ac740599701ecace716566ae2b",
			"env": {
				"client": "required",
				"server": "required"
			},
			"download_url": "/simply-cosmic-shading/version/0.1.6+cr0.3.0/simply-cosmic-shading-0.1.6-cr0.3.0.jar?isCdnReq=false"
		},
		{
			"type": "datamod",
			"id": "a-texture-pack",
			"version": "0.1.1",
			"sha512_hash": "266a2309edb7e07fa0baf0f89bcffdb2d56ed7fb8493970a7596056413bf72d9ca55ad68c6cc9216a13af9d355f43bb11b42cccc22cea1bacc74129af19d35c0",
			"env": {
				"client": "required",
				"server": "optional"
			},
			"download_url": "https://example.com/a-texture-pack/0.1.1.zip"
		}
	],
	"dependencies": {
		"cosmic-reach": "pre-alpha-0.3.1",
		"cosmic-quilt": "2.3.0"
	}
}
